server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 是否可以通过其他服务的serviceId来转发到具体的服务实例。默认为false
          # 为true,自动创建路由,路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: true
          lower-case-service-id: true
      routes:
        - id: path_route
          predicates:
            - Path=/api/server1/**
          uri: lb://server1:8001
          filters:
            - RewritePath=/api/server1, /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG

